/* Case-study content — single source of truth for /work pages. */

export const projects = [
  {
    slug: 'frequentor',
    nr: '01',
    group: 'Venture · Startup',
    title: 'Frequentor',
    hue: '#00d98e',
    motif: 'frequentor',
    category: 'Hospitality Intelligence',
    year: '2025 — Now',
    role: 'Founder · Sole engineer, designer & operator',
    status: 'Live pilot venues · Houston, TX',
    scope: 'Mobile · Cloud · Hardware · AI · GTM',
    link: { href: 'https://frequentor.com', label: 'frequentor.com' },
    tagline: 'The businesses you walk into every week know less about you than a website you visited <b>once</b>. I’m fixing that.',
    description: 'Hospitality intelligence platform: verified physical-presence signals connecting guests, staff, and owners. 9 U.S. provisional patents. Built solo.',
    thesis: [
      'Frequentor is a hospitality intelligence platform that connects guests, staff, and owners through <strong>verified physical-presence signals</strong>. A guest walks in, the system knows — silently, with permission — and everything downstream follows: loyalty that accrues from real visits, push campaigns whose attribution is a body through the door, and a live busyness score measured by hardware instead of guessed from check-ins.',
      'It is the flagship of everything on this site, and the reason most of the other projects exist. Every layer — the iOS/Android app, the AWS backend, the sensor firmware, the AI engine, the web platform, the patents, the sales motion — was designed, engineered, and shipped by <em>one person</em>.',
    ],
    build: [
      { label: 'MOBILE', title: '460+ file React Native / Expo app', body: 'Multi-role architecture (customer, staff, venue, ambassador, admin) on Expo Router. Native iOS modules for background geofencing, APNs push, Apple Wallet passes, and lock-screen widgets. OTA delivery via EAS Update; live on TestFlight with multi-device field validation.' },
      { label: 'CLOUD', title: 'AWS Amplify Gen 2 backend', body: 'AppSync GraphQL with live subscriptions, DynamoDB single-table design with GSIs, dual-mode Cognito (User + Identity Pools) under least-privilege IAM, Lambda functions, and S3 media pipelines. Production user pool serving live traffic in <code>us-east-1</code>.' },
      { label: 'HARDWARE', title: 'ESP32 sensor pucks — three signals fused', body: 'Custom firmware fusing mmWave radar (LD2450), thermal IR (AMG8833), and promiscuous-mode WiFi RSSI into a real-time busyness score at the edge. Enclosure designed in CAD and 3D-printed. Full sensing→bridge→AppSync→app chain confirmed live at a Houston venue in 2026.' },
      { label: 'AI', title: 'FAHE — the venue’s agentic layer', body: 'A proprietary fine-tuned LLM ("the GM who never sleeps") with five live tools wired to AppSync and Lambda: live stats, lapsed customers, financial KPIs, seat boosts, and shift alerts. Big enough to be its own case study — see №02.' },
      { label: 'WEB', title: 'Multi-tenant platform at frequentor.com', body: 'Express on Cloudflare with venue subsites at <code>/s/:slug</code>, three-tier Stripe billing, schema.org structured data, and full technical SEO. Plus a Remotion-based programmatic video-ad pipeline for venue marketing.' },
      { label: 'IP', title: 'Nine USPTO provisional patents', body: 'Geofence silent check-in, push attribution, presence-based loyalty, hardware fusion, verified-content authority, agentic forecasting, cross-venue intelligence, and demand forecasting — plus Authyr’s verified-attestation API. Prior-art research and the entire filing process handled personally, with more drafts queued for counsel.' },
      { label: 'GTM', title: 'Founder-led sales with a cold-start wedge', body: 'A $300 contest model to break the cold-start objection, an active Houston pilot pipeline, and a World Cup 2026 authority play: tourists from 32 countries authoring EXIF-geofence-verified articles for permanent multi-language SEO.' },
    ],
    signals: [
      { value: '9', label: 'U.S. PATENTS PENDING' },
      { value: '460+', label: 'FILES IN THE RN APP' },
      { value: '3', label: 'SENSOR MODALITIES FUSED' },
      { value: '5', label: 'LIVE AGENTIC TOOLS' },
    ],
    backers: [
      { icon: 'elevenlabs', name: 'ELEVENLABS', program: 'STARTUP GRANT' },
      { icon: 'nvidia', name: 'NVIDIA', program: 'INCEPTION' },
      { icon: 'aws', name: 'AWS', program: 'ACTIVATE' },
      { icon: 'anthropic', name: 'ANTHROPIC', program: 'BUILDER' },
      { icon: 'lambda', name: 'LAMBDA', program: 'FOR STARTUPS' },
      { icon: 'posthog', name: 'POSTHOG', program: 'FOR STARTUPS' },
      { icon: 'hubspot', name: 'HUBSPOT', program: 'FOR STARTUPS' },
    ],
    stack: ['React Native', 'Expo Router', 'TypeScript', 'AWS Amplify Gen 2', 'AppSync GraphQL', 'DynamoDB', 'Cognito', 'Lambda', 'S3 · IAM', 'ESP32 · C/C++', 'LD2450 mmWave', 'AMG8833 thermal IR', 'WiFi RSSI', 'BLE iBeacon', 'Express', 'Cloudflare', 'Stripe', 'EAS Build/OTA', 'AWS Bedrock', 'Anthropic Claude'],
    proves: [
      'This is what “full-stack” actually means to me: from radar firmware on a bench to IAM policies to App Store submission to the patent language protecting all of it. One person, every layer, production traffic.',
    ],
  },

  {
    slug: 'fahe',
    nr: '02',
    group: 'Venture · Applied AI',
    title: 'FAHE',
    hue: '#7c5cff',
    motif: 'fahe',
    category: 'Proprietary LLM Engine',
    year: '2026',
    role: 'ML engineer · Data, training, evals, serving',
    status: 'In production behind live venue demos',
    scope: 'Fine-tuning · Quantization · Evals · Voice',
    tagline: 'The GM who never sleeps — a fine-tuned model that answers like an <b>operator</b>, not a chatbot.',
    description: 'A custom fine-tuned LLM for hospitality operations: 40+ training runs, a 410-test eval battery at 99%, GGUF quantization, and an inference-orchestration layer.',
    thesis: [
      'Frequentor’s venues needed an AI that reads a live data snapshot — occupancy, revenue, lapsed customers, staffing, food cost — and returns <strong>one decisive, GM-grade action</strong>. No hedging, no invented numbers, no pretending to see data the POS doesn’t expose. Commodity API models couldn’t hold that persona reliably, and per-query economics at venue scale demanded a small local model.',
      'So I built FAHE — the Frequentor Agentic Hospitality Engine — the hard way: my own datasets, my own fine-tunes, my own eval harness, my own serving stack. Over <em>40 model versions</em> across two base architectures, and an ending most ML teams would recognize: the winning system wasn’t the biggest model, it was the best-orchestrated one.',
    ],
    build: [
      { label: 'TRAINING', title: '40+ fine-tune iterations', body: 'Mistral-7B-Instruct LoRA/QLoRA via Unsloth (rank 16, RSLoRA, all 7 target modules, 4-bit NF4) on a single RTX 5070 Ti. Hand-built datasets grew from 6,841 to 12,441 instruction pairs, with per-version “surgical” datasets generated by dedicated scripts.' },
      { label: 'SCALE TRACK', title: 'Llama-3.3-70B in the cloud', body: 'QLoRA on Lambda H100s, managed fine-tunes on Azure AI Foundry, then adapter merge → S3 → AWS Bedrock custom-model import. The 70B raw model lost to the orchestrated 7B on the battery — and I kept the receipts.' },
      { label: 'QUANT + SERVE', title: 'GGUF pipeline to production', body: 'Merge → BF16 GGUF via llama.cpp → Q4_K_M (4.07 GB for the 7B). Served through LM Studio behind a Node gateway with agentic tool routing to five live AppSync/Lambda tools, exposed remotely over Tailscale + Cloudflare tunnels.' },
      { label: 'EVALS', title: 'A 410-test decision-grade battery', body: '41 scenarios × 10 real-venue profiles, plus a 120-test conversational battery. Category scoring across diagnostics, revenue, anti-hallucination, counterfactuals, and time pressure — with named failure patterns and token-level forensics for every regression.' },
      { label: 'ORCHESTRATION', title: 'The 94% → 99% decision', body: 'Instead of training version 45, I built an inference-layer sanitizer — negation-aware output repair, decisiveness rewrites, meta-leak stripping — that lifted the frozen v11 weights from 94% to <code>404/410 (99%)</code> with zero retraining. Knowing when to stop training is the skill.' },
      { label: 'SIMULATOR', title: 'Anti-hallucination by design', body: 'A Python/SQLite venue simulator (101 MB of synthetic Toast-style POS data) where each venue gets a different POS provider profile and a visibility engine masks the fields that provider can’t see — so the model learns to say “I don’t have that data.”' },
      { label: 'VOICE', title: 'A spoken operator', body: 'ElevenLabs streaming TTS conductor with barge-in, SSML break injection, and number normalization — about 593 ms to first audio. 18/18 end-to-end voice tests passing.' },
      { label: 'THE METAL', title: 'Blackwell debugging diaries', body: 'Documented and fixed TorchInductor/Triton crashes on sm_120, fused cross-entropy OOMs, and stale compile-cache corruption — the unglamorous 20% that makes local training on brand-new silicon actually work.' },
    ],
    signals: [
      { value: '40+', label: 'MODEL VERSIONS TRAINED' },
      { value: '99%', label: 'EVAL BATTERY — 404/410' },
      { value: '12,441', label: 'TRAINING PAIRS (PEAK SET)' },
      { value: '593ms', label: 'VOICE TIME-TO-FIRST-AUDIO' },
    ],
    stack: ['PyTorch', 'Unsloth', 'TRL / PEFT', 'QLoRA · BitsAndBytes', 'Mistral-7B', 'Llama-3.3-70B', 'llama.cpp · GGUF', 'LM Studio', 'Lambda H100', 'Azure AI Foundry', 'AWS Bedrock', 'Node.js gateway', 'SQLite simulator', 'ElevenLabs TTS', 'Tailscale · Cloudflare'],
    proves: [
      'The full ML lifecycle, solo: dataset design → fine-tuning → quantization → serving → evaluation → orchestration. And the judgment layer on top: measuring everything, freezing the weights when the data said so, and getting the last five points from engineering instead of compute.',
    ],
  },

  {
    slug: 'veridose',
    nr: '03',
    group: 'Venture · Startup',
    title: 'Veridose',
    hue: '#2e6bff',
    motif: 'veridose',
    category: 'Radiation-Oncology AI',
    year: '2026',
    role: 'Co-founder · Engineering, product, design',
    status: 'Working demo · Investigational, not clinical',
    scope: 'Medical imaging · ML inference · Trust systems',
    tagline: 'Anyone can ship an auto-contour model. The question is: who <b>signs their name</b> to it?',
    description: 'Verified radiation-oncology AI: nnU-Net auto-contouring on real CT data, an in-browser 3D medical viewer, and a hash-chained physicist attestation ledger.',
    thesis: [
      'In radiation therapy, clinicians hand-trace every organ on every CT slice — the contour <strong>is</strong> the treatment plan. It’s slow, and it fails exactly where it matters most: the prostate/bladder/rectum region has almost no visible density edge for classical tools to find.',
      'Veridose’s answer is two-sided. Technically: AI contouring built on learned 3D shape priors rather than pixel intensity. Commercially: <em>accountability as the moat</em> — every model release reviewed and cryptographically signed by a named, board-certified medical physicist (my co-founder, Maurice Tajiran, MS, DABR), with public per-anatomy benchmarks and a tamper-evident audit trail.',
    ],
    build: [
      { label: 'INFERENCE', title: 'A real auto-contour API', body: 'FastAPI service running TotalSegmentator (nnU-Net v2) on staged CT cases with GPU inference on an RTX 5070 Ti. Per-anatomy NIfTI masks stream into a multi-label volume one file at a time — holding RAM near 80 MB instead of ~3 GB.' },
      { label: 'PROOF', title: 'Quantifying why intensity fails', body: 'On a real pelvis CT (public TCIA data — no PHI ever committed), the pipeline measured that ~80% of soft-tissue voxels have sub-threshold gradient: there is literally no edge to segment. That number is the thesis — shape priors or nothing.' },
      { label: 'VIEWER', title: 'In-browser 3D medical imaging', body: 'A NiiVue-based multiplanar viewer overlaying ten segmented structures on the CT with per-structure colormaps, opacity controls, slice scrubbing, and axial / coronal / sagittal / 3D modes.' },
      { label: 'LEDGER', title: 'witness.py — the trust primitive', body: 'A hash-chained, tamper-evident ledger for linac calibration attestations (TG-51 / TG-142). Flip a single byte anywhere in history and the chain visibly breaks; validation runs on every read. The signature-as-moat thesis, embodied in code.' },
      { label: 'SHADER', title: 'Hand-written WebGL scanner', body: 'A from-scratch GLSL fragment shader — FBM tissue grain, a sweeping scan line, converging dose beams, pulsing isodose rings — with a 30 fps cap, DPR clamping, IntersectionObserver pausing, context-loss recovery, and full reduced-motion fallback.' },
      { label: 'SITE', title: 'Clinical-grade marketing front', body: 'Next.js 16 / React 19 / Tailwind v4 with bespoke effects (no component library), NASA-blue trust palette, monospace verification motifs, and honest labeling: every illustrative number marked as such.' },
    ],
    signals: [
      { value: '10', label: 'STRUCTURES RENDERED IN 3D' },
      { value: '~80MB', label: 'INFERENCE RAM (VS ~3GB NAIVE)' },
      { value: '0', label: 'PATIENT RECORDS TOUCHED — PUBLIC DATA ONLY' },
    ],
    stack: ['Python', 'FastAPI', 'PyTorch cu128', 'TotalSegmentator', 'nnU-Net v2', 'SimpleITK', 'pydicom · nibabel', 'NiiVue', 'WebGL / GLSL', 'Next.js 16', 'React 19', 'Tailwind v4', 'Netlify', 'Tailscale Funnel'],
    proves: [
      'That I can walk into a regulated, unforgiving domain — medical physics — and ship a working end-to-end system: real GPU inference, real 3D visualization, real cryptographic audit machinery, and marketing that respects the line between demo and clinic.',
    ],
  },

  {
    slug: 'authyr',
    nr: '04',
    group: 'Venture · Startup',
    title: 'Authyr',
    hue: '#ff5c28',
    motif: 'authyr',
    category: 'Cryptographic Trust Rails',
    year: '2026',
    role: 'Founder · Sole engineer',
    status: 'Marketing live · MVP in build (Aug 2026)',
    scope: 'Applied cryptography · SaaS · IP strategy',
    link: { href: 'https://authyr.com', label: 'authyr.com' },
    tagline: 'Neutral evidence for every dispute — receipts that <b>can’t be rewritten</b>.',
    description: 'A cryptographic evidence layer for consumer-service disputes: ed25519 hash-chained attestations, a 30-day mitigation window, and an AWS Amplify Gen 2 backend.',
    thesis: [
      'Every dispute forum — BBB, chargebacks, small claims, licensing boards — adjudicates <strong>without neutral evidence</strong>. Authyr is that evidence: a portable, independently verifiable, cryptographically signed receipt that a real customer interaction happened, plus a 30-day pre-publish mitigation window that gives businesses a chance to fix things before a review goes public. Affirmation, not censorship.',
      'The design is deliberately patent-aware: engineered around GPS-location prior art (Chen US 9,842,340) with a multi-signal, non-GPS verification stack — and its own provisional patent filed at the USPTO (App # 64/069,215).',
    ],
    build: [
      { label: 'TRUST RAILS', title: 'Append-only ed25519 hash chains', body: 'Each business gets a chain where every entry hashes <code>canonical({payload, prevHash, publicKeyId})</code> from a genesis hash. Mutate any past attestation and every later link breaks. Third parties verify fully offline against published <code>.well-known</code> keys.' },
      { label: 'CRYPTO AGILITY', title: 'Built to outlive its own algorithms', body: 'Key IDs encode rotation years and every signed envelope stamps its hash algorithm, so keys and hashes (SHA-256 → SHA-3) can migrate with zero chain rewrites. Distinct envelope types prevent cross-replay between attestations, articles, and reviews.' },
      { label: 'PRODUCT', title: 'The resolution arc', body: 'A 1★ complaint that becomes a 5★ recovery is provable end-to-end as two chained review entries — “submitted” then “sealed.” The mitigation window is enforced server-side by a scheduled expiry Lambda, not by promises.' },
      { label: 'BACKEND', title: 'Amplify Gen 2, done properly', body: 'Six DynamoDB tables, Cognito custom-auth magic links (three challenge Lambdas), SES email, owner-scoped authorization with server-side IAM writers for webhooks, and Stripe Connect — where payment itself becomes a verification signal.' },
      { label: 'AI', title: 'A draft-only reputation agent', body: 'A pure, unit-testable prompt builder under hard rules: never posts, never invents facts, never leaks PII — it cites the verifiable receipt URL instead of arguing with anyone.' },
      { label: 'SEEDING', title: 'Cold-start from public records', body: 'A trust-score engine ingesting Texas TDLR license data with §230-aware public/private field separation — so day-one pages are useful without a single signup.' },
    ],
    signals: [
      { value: '22.6k', label: 'LINES OF FIRST-PARTY TS' },
      { value: '30', label: 'DAY MITIGATION WINDOW' },
      { value: '6', label: 'DYNAMODB TABLES' },
    ],
    stack: ['Next.js 16', 'React 19', 'TypeScript', 'Tailwind v4', 'shadcn / Base UI', 'AWS Amplify Gen 2', 'DynamoDB', 'Cognito custom auth', 'Lambda · SES · CDK', '@noble/curves ed25519', 'Stripe Connect', 'Vitest', 'Netlify · Vercel'],
    proves: [
      'Applied cryptography in a shipping product — not a toy chain, but one with rotation, algorithm agility, replay protection, and offline verification. Plus the founder layer: prior-art navigation, patent posture, and §230-aware data design.',
    ],
  },

  {
    slug: 'hydrova',
    nr: '05',
    group: 'Venture · Concept',
    title: 'Hydrova',
    hue: '#35e0d6',
    motif: 'hydrova',
    category: 'Water Infrastructure Venture',
    year: '2026',
    role: 'Venture designer',
    status: 'Concept · Investor deck',
    scope: 'Product architecture · Brand · IP posture',
    tagline: 'What if the water-heater closet became the <b>smartest room</b> in the house?',
    description: 'Venture design for a patent-pending residential water platform: HYDROVA CORE V1.1 — modular, sensor-laden, cloud-synced infrastructure to replace the tank water heater.',
    thesis: [
      'Residential water infrastructure is 1970s technology wearing a new jacket: a dumb tank, a pressure valve, and a prayer. Hydrova reimagines that closet as a platform — <strong>HYDROVA CORE V1.1</strong>, an integrated, modular water-management system: on-demand heating, filtration-ready plumbing, instant leak response, and a cloud-synced health index for the whole house.',
      'This one hasn’t shipped — and that’s the point of including it. The deck specs a 125 PSI ceiling, 0.05-second response time, real-time cloud sync, and an “Efficiency Core” optimization loop. Getting there meant learning enough plumbing code, sensor economics, and appliance supply-chain reality to know exactly what V1.1 would take.',
    ],
    build: [
      { label: 'PRODUCT', title: 'Platform, not appliance', body: 'A modular core that replaces the tank heater and absorbs adjacent jobs — filtration, leak shutoff, pressure management — with a health index as the consumer-facing metric. Architecture designed for module upgrades instead of unit replacement.' },
      { label: 'IDENTITY', title: 'A brand built for trust at 125 PSI', body: 'Deep-navy and mint identity with kinetic typography, spec-forward hero (“REIMAGINING RESIDENTIAL WATER SYSTEMS”), and an Investor Relations mode — designed to read as infrastructure, not gadget.' },
      { label: 'NARRATIVE', title: 'An interactive pitch system', body: 'The deck is a web presentation, not slides: problem → platform → device specs → market, with live spec readouts (max pressure, response time, cloud sync) rendered like a product dashboard.' },
      { label: 'IP', title: 'Patent-pending posture from day zero', body: 'Positioned around defensible integration claims rather than commodity parts — the same IP-first discipline applied at Frequentor and Authyr.' },
    ],
    signals: [
      { value: '125', label: 'PSI MAX PRESSURE (SPEC)' },
      { value: '0.05s', label: 'RESPONSE TIME (SPEC)' },
    ],
    stack: ['Venture design', 'Product architecture', 'Industrial-design direction', 'Brand system', 'Investor narrative', 'Google AI Studio'],
    proves: [
      'Not every venture ships; every venture teaches. Hydrova is the 0→1 muscle in isolation: taking a category most people never think about, finding the platform inside it, and packaging product, brand, and IP posture into something an investor can evaluate in five minutes.',
    ],
  },

  {
    slug: 'thisiscredit',
    nr: '06',
    group: 'Venture · Product build',
    title: 'This Is Credit',
    hue: '#ffd23f',
    motif: 'thisiscredit',
    category: 'Consumer Fintech',
    year: '2026',
    role: 'Architect · Engineer',
    status: 'Phase-0 prototype · Deployed on Netlify',
    scope: 'Architecture · Data viz · Compliance',
    tagline: 'One dashboard for a financial identity scattered across <b>nine industries</b>.',
    description: 'A consumer financial-health platform: three-bureau credit, disputes, business credit, public records, and mortgage readiness — behind a swap-one-file provider abstraction.',
    thesis: [
      'Your financial identity lives in fragments: three consumer bureaus, D&amp;B for your business, public-records vendors, identity brokers, mortgage underwriters. This Is Credit (built for Bolt Credit Services) consolidates all of it into one consumer dashboard — monitoring, disputes, business credit, and mortgage readiness.',
      'The architectural bet: the UI must <strong>never touch a vendor API directly</strong>. Every data source sits behind a vendor-independent provider interface, so graduating from demo data to Xactus, D&amp;B Direct+, LexisNexis, or Persona means writing one adapter file — with zero UI changes.',
    ],
    build: [
      { label: 'ARCHITECTURE', title: 'The provider abstraction layer', body: 'A richly-typed domain model — bureau scores, credit accounts, disputes, PAYDEX, public records, KYC consent — with a single-line provider registry mapping every layer to its implementation. The expensive integrations are designed before they’re bought.' },
      { label: 'DATA VIZ', title: 'Charts with zero chart libraries', body: 'A hand-rolled inline-SVG three-bureau trend chart: computed axis ticks, hover crosshair and tooltip, animated end markers, a single selective direct label to avoid collisions, and a <code>&lt;details&gt;</code> data-table fallback for accessibility.' },
      { label: 'MOTION', title: 'Dependency-free canvas plexus', body: 'The hero renders a drifting, proximity-linked network of data-source nodes feeding one dashboard — theme-aware, reduced-motion-compliant, offscreen-paused, with gentle cursor repulsion. It replaced an earlier WebGL aurora after honest performance review.' },
      { label: 'ENGINE', title: 'Real mortgage math', body: 'Middle-of-three-bureau score selection, DTI computation, FHA / VA / Conventional qualification flags, and a weighted 0–100 readiness composite surfaced through a live calculator.' },
      { label: 'COMPLIANCE', title: 'Docs before data', body: 'FCRA permissible purpose, CROA disclosures, GLBA safeguards, and state CSO registration mapped in writing before any real consumer data is allowed near the system.' },
    ],
    signals: [
      { value: '3', label: 'BUREAUS MODELED' },
      { value: '0', label: 'CHART LIBRARIES' },
      { value: '1', label: 'ADAPTER FILE PER VENDOR SWAP' },
    ],
    stack: ['Next.js 16', 'React 19', 'TypeScript', 'Tailwind v4', 'Motion', 'Inline SVG charts', 'Canvas 2D', 'Netlify'],
    proves: [
      'Architecture discipline: designing for the integration you haven’t paid for yet, hand-building the visualization layer to an accessibility spec, and treating compliance as a design input instead of an afterthought.',
    ],
  },

  {
    slug: 'alitherep',
    nr: '07',
    group: 'Client · Web design',
    title: 'AliTheRep',
    hue: '#c8ff3d',
    motif: 'alitherep',
    category: 'Client Platform Redesign',
    year: '2026',
    role: 'Designer · Engineer (client work)',
    status: 'Live in production',
    scope: 'Web · Motion · Deploy pipeline',
    link: { href: 'https://www.alitherep.com', label: 'alitherep.com' },
    tagline: 'A one-man sales territory deserves a <b>platform</b>, not a brochure.',
    description: 'Full redesign of alitherep.com for an independent cycling sales rep covering TX/LA/OK — volt-on-ink design system, Remotion kinetic hero, dealer portal, dual-deploy pipeline.',
    thesis: [
      'Ali represents cycling brands — Kali, Mavic, Retrospec, Selle Italia, Northwave and more — to dealers across Texas, Louisiana, and Oklahoma. His old site said “business card.” The job: make it say <strong>platform</strong> — for the brands he pitches and the dealers he serves.',
      'The redesign treats a solo rep like a serious B2B operation: a volt-on-ink identity, a kinetic-typography hero rendered with Remotion, a brand catalog driven from typed data, and a dealer portal — shipped live on the client’s real domain and iterated against his notes.',
    ],
    build: [
      { label: 'DESIGN', title: 'Volt-on-ink system', body: 'A high-contrast identity built in Tailwind v4 with shadcn-style primitives — engineered to make a one-person operation read like a brand dealers trust with their orders.' },
      { label: 'MOTION', title: 'Remotion hero on the web', body: 'The kinetic-typography hero is a Remotion composition embedded via <code>@remotion/player</code> — programmatic video as a landing-page element, not an MP4.' },
      { label: 'PORTAL', title: 'Dealer portal', body: 'A routed <code>/portal</code> experience for B2B dealers, currently demo-grade, structured for account features as the rep’s book grows.' },
      { label: 'PIPELINE', title: 'Asset + deploy automation', body: 'Puppeteer + sharp scripts scrape and optimize brand imagery to WebP with generated manifests. Dual deploy targets: GitHub Pages via Actions and HostGator via scripted cPanel push, with a PHP contact endpoint.' },
      { label: 'CLIENT LOOP', title: 'Real stakeholder iteration', body: 'Logo, palette, portal branding, and contact-form fixes shipped in response to client notes — the unglamorous rhythm of client work, done properly.' },
    ],
    signals: [
      { value: '7+', label: 'BRANDS IN THE CATALOG' },
      { value: '2', label: 'DEPLOY TARGETS, ONE COMMAND' },
    ],
    stack: ['Vite', 'React 19', 'TypeScript', 'Tailwind v4', 'Remotion / @remotion/player', 'React Router', 'puppeteer-core · sharp', 'GitHub Actions', 'PHP · cPanel', 'Cloudflare DNS'],
    proves: [
      'Client delivery end-to-end: design system, motion engineering, data-driven content, deployment automation, and the discipline of shipping against someone else’s feedback on someone else’s domain.',
    ],
  },

  {
    slug: 'cruise-reels',
    nr: '11',
    group: 'Work improvisation · PTC',
    title: 'Cruise Reels',
    hue: '#ff4f9a',
    motif: 'cruise',
    category: 'Programmatic Video',
    year: '2026',
    role: 'Motion engineer',
    status: 'Shipped · Rendering pipeline live',
    scope: 'Video-as-code · Ad creative',
    tagline: 'Twelve ad variants. One codebase. <b>Zero timelines</b> dragged around an editor.',
    description: 'A Remotion pipeline rendering 12 vertical cruise-vacation ad reels (1080×1920) as code — shared motion library, spring physics, parameterized scenes.',
    thesis: [
      'Short-form ad creative dies by iteration cost: every variant is another afternoon in a video editor. Cruise Reels treats the ad as <strong>software</strong> — twelve 1080×1920 vertical compositions written in React, rendered to H.264 by CLI, each 12–15 seconds of parameterized scenes over stock cruise footage.',
      'Fifteen years of running paid media taught me what the creative needs to say; Remotion let me encode it once and render it twelve ways.',
    ],
    build: [
      { label: 'PIPELINE', title: '12 compositions, one render command', body: 'Ad1–Ad12 registered in a single root, each 1080×1920 @ 30fps, ~360–450 frames, rendered to separate MP4s via <code>remotion render</code>.' },
      { label: 'LIBRARY', title: 'A shared motion vocabulary', body: 'Reusable <code>FootageBackdrop</code> (full-bleed OffthreadVideo with configurable legibility gradients), a <code>Caption</code> component with an inline accent-word mini-parser, spring-pulsed CTA buttons, and phone/text response rows.' },
      { label: 'PHYSICS', title: 'Frame-driven animation', body: 'Everything keyed to <code>useCurrentFrame</code> — spring() entrances, staggered thumbnail fly-ins, interpolated easings — deterministic, reviewable, diffable motion.' },
      { label: 'BRAND', title: 'Centralized art direction', body: 'One coral/gold/navy/cream palette and shared shadow constants keep twelve ads reading as one campaign.' },
    ],
    signals: [
      { value: '12', label: 'AD COMPOSITIONS' },
      { value: '1080×1920', label: '@ 30FPS VERTICAL' },
      { value: '~5.9k', label: 'LINES OF TSX' },
    ],
    stack: ['Remotion 4', 'React 19', 'TypeScript', 'spring() physics', 'OffthreadVideo', 'H.264 render pipeline'],
    proves: [
      'The marketer and the engineer in one workflow: ad creative that scales like software, informed by a decade and a half of actually buying the media it’s made for.',
    ],
  },

  {
    slug: 'newspeed',
    nr: '08',
    group: 'Client · Web design',
    title: 'Newspeed',
    hue: '#ff3d3d',
    motif: 'newspeed',
    category: 'Automotive Web',
    year: '2026',
    role: 'Designer · Engineer (client work)',
    status: 'Delivered',
    scope: 'Web · Brand · Trust design',
    tagline: 'Local trust, <b>engineered</b> — a body shop that finally looks like its work.',
    description: 'Marketing site for a family-owned Austin auto body shop: React 19 + Vite SPA, video hero, brand token system, motion entrances.',
    thesis: [
      'Newspeed Automotive is a family-owned body and mechanical shop in Austin. Its customers decide in thirty seconds whether to trust a shop with a five-figure repair — so the site’s whole job is <strong>credibility at a glance</strong>: certified work, ten years of history, real reviews, and a frictionless path to a quote.',
    ],
    build: [
      { label: 'APP', title: 'Clean four-route SPA', body: 'React 19 + Vite with React Router 7 — Home, Services, About, Contact — shared Navbar/Footer, and Motion entrance animations tuned to stay out of the way.' },
      { label: 'HERO', title: 'Video-first trust shot', body: 'Autoplaying looped hero video with image fallback and a legibility overlay — shop-floor footage doing the arguing.' },
      { label: 'SYSTEM', title: 'Brand tokens over one-off styles', body: 'Custom Tailwind tokens (<code>brand-blue</code>, <code>brand-red</code>, neutrals) keep every page on-palette and make client revisions one-line changes.' },
      { label: 'ASSETS', title: 'Self-hosted media', body: 'All imagery and video localized into the repo after hotlink breakage — boring, correct, and fast.' },
    ],
    signals: [
      { value: '4', label: 'ROUTES, ZERO CLUTTER' },
      { value: '~939', label: 'LINES OF TSX — LEAN' },
    ],
    stack: ['React 19', 'Vite 6', 'TypeScript', 'Tailwind v4', 'Motion', 'React Router 7'],
    proves: [
      'Small-scope discipline: a lean, token-driven build where the restraint is the craft — every element earns its place, and the client can maintain it.',
    ],
  },

  {
    slug: 'ptc-promotions',
    nr: '10',
    group: 'Work improvisation · PTC',
    title: 'PTC Promotions',
    hue: '#38b6ff',
    motif: 'ptc',
    category: 'Growth Engineering',
    year: '2026',
    role: 'Growth engineer',
    status: 'Deploy-ready · Awaiting CRM keys',
    scope: 'Funnels · A/B systems · CRM integration',
    tagline: 'The funnel <b>is</b> the product.',
    description: 'Cruise-giveaway lead-gen system: three A/B landing variants plus a branching multi-step qualifying survey wired for GoHighLevel, built dependency-free.',
    thesis: [
      'Lead generation for cruise expos targeting affluent 55+ travelers — where the asset isn’t the landing page, it’s the <strong>qualification logic</strong>. A giveaway pulls thousands of entries; the business only wants the ones who’ve cruised before and will again.',
      'Built dependency-free on purpose: pure HTML/CSS/JS that any hosting stack can serve and any CRM can consume. Fifteen years of funnel craft, no framework required.',
    ],
    build: [
      { label: 'A/B SYSTEM', title: 'Three landing architectures', body: 'Split-screen hero, full-screen video hero, and frosted-glass card — three genuinely different conversion hypotheses sharing one token system, ready for traffic-split testing.' },
      { label: 'SURVEY', title: 'A branching qualifying engine', body: 'A ~900-line self-contained multi-step survey: five-step progress model, radio and multi-select questions, and conditional logic that routes first-time cruisers to a consolation path while qualified leads see the full prize set.' },
      { label: 'CRM', title: 'GoHighLevel handoff', body: 'FormData → structured payload → webhook POST into GHL automations, with success states and phone-fallback error handling. TCPA-compliant consent language built in.' },
      { label: 'AUDIENCE', title: 'Designed for 55+', body: 'Large type, high contrast, generous targets — accessibility as conversion strategy, documented across four setup and integration guides.' },
    ],
    signals: [
      { value: '3', label: 'A/B LANDING VARIANTS' },
      { value: '0', label: 'DEPENDENCIES' },
    ],
    stack: ['HTML5', 'CSS3', 'Vanilla JS', 'GoHighLevel', 'TCPA compliance', 'A/B methodology'],
    proves: [
      'Growth engineering as a discipline: conversion architecture, qualification logic, and CRM plumbing — the skills behind the 6,500% renewal lift and 400% ROI campaigns on the résumé, expressed as shippable code.',
    ],
  },

  {
    slug: 'ghl-rc-bridge',
    nr: '09',
    group: 'Work improvisation · PTC',
    title: 'GHL×RC Bridge',
    hue: '#ffb02e',
    motif: 'bridge',
    category: 'Systems Integration',
    year: '2026',
    role: 'Systems engineer (day-job improvisation)',
    status: 'Deployed · Netlify Functions',
    scope: 'Webhooks · APIs · Serverless',
    tagline: 'The CRM couldn’t hear the phone system. So I built it <b>an ear</b> — in five serverless functions.',
    description: 'A bidirectional SMS/MMS bridge between RingCentral and GoHighLevel: webhook sync, conversation threading, and campaign keyword automation on Netlify Functions.',
    thesis: [
      'At Professional Travel Center, the phones live on RingCentral and the CRM lives in GoHighLevel — and out of the box, neither knows the other exists. Every customer text was invisible to the system of record; every agent reply lived in the wrong tool.',
      'No vendor sold the fix, so I built it: a <strong>bidirectional SMS/MMS bridge</strong>. Inbound texts thread into the right GHL conversation with contact upsert; agent replies in GHL go out through RingCentral and log back into the thread; and campaign keywords — the cruise-expo finalist numbers from №10 — trigger an automatic confirmation MMS. A phone line became an automation surface.',
    ],
    build: [
      { label: 'INBOUND', title: 'RingCentral webhooks, handled properly', body: 'Message-store notifications with the RC validation-token handshake, full message fetch, phone-number contact matching with upsert, and conversation threading into GoHighLevel — <code>rc-inbound.js</code>.' },
      { label: 'OUTBOUND', title: 'Closing the loop without echo', body: 'GHL webhook → RingCentral SMS send → logged back to the same GHL thread, so agents work in one tool and customers see one number.' },
      { label: 'AUTOMATION', title: 'Keyword-triggered MMS', body: 'Finalist-number detection fires a confirmation MMS automatically — the integration hook that made the PTC Promotions giveaway funnel self-service.' },
      { label: 'SURFACES', title: 'Two zero-dependency consoles', body: 'A ~730-line inbox viewer and a ~500-line composer in plain HTML/JS, served from the same Netlify deploy — no framework, no build, no login walls between an agent and a reply.' },
      { label: 'ITERATION', title: 'v1 → v4', body: 'Four shipped revisions of auth handling (<code>rcAuth.js</code>), GHL API wrappers, and subscription management — the version trail of a tool that people actually used.' },
    ],
    signals: [
      { value: '5', label: 'SERVERLESS FUNCTIONS' },
      { value: '2-WAY', label: 'SMS / MMS SYNC' },
      { value: 'v4', label: 'SHIPPED REVISIONS' },
    ],
    stack: ['Node.js', 'Netlify Functions', 'RingCentral API', 'GoHighLevel API', 'Webhooks', 'OAuth / token auth', 'Vanilla JS consoles'],
    proves: [
      'The improviser’s skillset: read two vendors’ API docs, find the seam, and ship a working bridge without asking permission or budget. Most of a marketer-engineer’s value lives in exactly this kind of unglamorous connective tissue.',
    ],
  },
];
